import os
import keyboard
import time
import pyttsx3
from pynput.keyboard import Key, Controller
keyboard1=Controller()
engine=pyttsx3.init()
sound=engine.getProperty('voices')
engine.setProperty('voice',sound[1].id)
os.system("color a")
os.system("cls")
print("____________________                 _____                     .__                       __                ")
print("\______   \____    /____   ____     /  _  \   ____  ____  ____ |  |   ________________ _/  |_  ___________ ")
print(" |     ___/ /     // __ \_/ __ \   /  /_\  \_/ ___\/ ___\/ __ \|  | _/ __ \_  __ \__  \\   __\/  _ \_  __ \"")
print(" |    |    /     /\  ___/\  ___/  /    |    \  \__\  \__\  ___/|  |_\  ___/|  | \// __ \|  | (  <_> )  | \/")
print(" |____|   /_______ \___  >\___  > \____|__  /\___  >___  >___  >____/\___  >__|  (____  /__|  \____/|__|   ")      
print("                  \/   \/     \/          \/     \/    \/    \/          \/           \/                   ")
print("Initializing")
print("Please Wait PZee Accelerator is Accelerating your PC")
os.system("ipconfig/flushDNS")
print("10% Completed...")
os.system(" del /q/f/s %TEMP%\*")
print("40% Completed...")
os.system("del C:\Windows\Prefetch\*.* /Q")
print("63% Completed...")
os.system("del /s /f /q c:\windows\temp\*.*")
print("85% Completed...")

                                                                      
keyboard.press_and_release('win+r')
time.sleep(1)
keyboard1.type('recent')
keyboard.press_and_release('enter')
time.sleep(2)
keyboard.press_and_release('ctrl+a')
time.sleep(2)
keyboard.press_and_release('shift+delete')
time.sleep(3)
keyboard.press_and_release('alt+f4')
print("92% Completed...")
os.system("start shell:RecycleBinFolder")
time.sleep(2)
keyboard.press_and_release('ctrl+a')
time.sleep(2)
keyboard.press_and_release('shift+delete')
time.sleep(1)
keyboard.press_and_release('enter')
time.sleep(5)
keyboard.press_and_release('alt+f4')
print("100% Completed...")

